version: '3.3'

services:
  eric-proxy:
    restart: always
    build: ./
    working_dir: /proxyapp/
    ports:
      - '4002:4002'
    command: bash -c "npm install && npm run start"
    volumes:
      - ./:/proxyapp
